### PR TITLE
fix: Incorrectly storing the image pointer in the cache

### PR DESCRIPTION
**Pull request by iQQBot**
This PR changes the structure stored in the cache, excluding the image Pointer. 

This is because there might be multiple pods using the same image, but their index in the pod is not the same. 

Incorrect caching will lead to errors in the container index, resulting in replacement with the wrong image.

### CODE REVIEW

**Comment by kylos101** [comment]
👋 hey @JimBugwadia,

@iQQBot and I are new here. Let us know if we can do anything better to be consistent with how y'all do things?

We bumped into a bug when testing `kyverno-notation-aws`, and found sometimes the container images are not set right. For example, given a pod containing redis and kube-rbac-proxy containers with the correct image, after mutation, the image for redis will instead point at the image for kube-rbac-proxy.

A couple question:
1. Do you already have an issue for this, or would you like us to create one?
2. How would you like us to do testing?

Thanks a lot for any support you can provide. Take care!

**Comment by vishal-chdhry** [comment]
thank you so much @iQQBot and @kylos101 for working on this, I will add a few things here for testing just to be sure this colision does not happen.

Sorry it took so long, I missed the PR entirely

**Review by vishal-chdhry — APPROVED** [review]

**Review by realshuting — APPROVED** [review]

**Comment by kylos101** [comment]
Thank you @vishal-chdhry and @realshuting for the additional commit and review ! Are you able to forecast when when this might be included as part of `kyverno-notation-aws`? I ask because that'll help us understand when we would then be able to remove our related forks.

**Comment by vishal-chdhry** [comment]
I will cut a new release by monday

**Comment by vishal-chdhry** [comment]
@iQQBot @kylos101 you can use the latest manifest now, it should work

**Pull request merged**
